# Generated by Django 2.2.10 on 2021-01-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polls_text', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(verbose_name='Начало опроса')),
                ('end_date', models.DateTimeField(verbose_name='Конец опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Polls')),
                ('question_text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=120)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
